### ISSUE TITLE
Wrong hoverstate with smooth chat messages

### ISSUE THREAD

**Issue by romangraef** [Polyfrost/Chatting#17] opened 2023-01-16 14:13 UTC
![image](https://user-images.githubusercontent.com/20768569/212661303-4b1177a3-a6a0-40e5-a243-78ee2a82e6f3.png)
Prevents clicking on message actions and copying chat.

**Comment by Wyvest** [comment] 2023-01-20 14:23
> ![image](https://user-images.githubusercontent.com/20768569/212661303-4b1177a3-a6a0-40e5-a243-78ee2a82e6f3.png)
> Prevents clicking on message actions and copying chat.

are you sure this is a thing with smooth chat messages or is it smooth scrolling

**Comment by Wyvest** [comment] 2023-01-20 14:35
also i cant reproduce the issue with chatting + patcher

**Comment by Wyvest** [comment] 2023-02-25 01:00
cannot reproduce, closing

**Closed by Wyvest** 2023-02-25 01:00 UTC

**Comment by romangraef** [comment] 2023-02-25 11:47
Oh yeah, me neither nowadays, not sure when or what fixed it
